[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 105
target-version = ["py36"]

[tool.isort]
line-length = 105
profile = "black"
